#!/bin/bash
urouter_dir="/urouter"
source $urouter_dir/urouter.uconf
mkdir -p $uetc/ppp
echo "### URouter PPPOE Config ###
#noipdefault
#defaultroute
#replacedefaultroute
hide-password
#lcp-echo-interval 1
#lcp-echo-failure 12
noauth
noaccomp
mtu 1492
mru 1492
#persist
#maxfail 100
#holdoff 200000000
plugin rp-pppoe.so $cableinterfaceuconf
user $pppuseruconf
password $ppppassworduconf
#usepeerdns
#-ac
#-am
#-pc
+ipv6
#ipv6cp-accept-local
#+ipv6 ipv6cp-use-ipaddr
#-ip
#-mn
silent
#passive
#asyncmap a
#domain $domainname4uconf
#ipx
mrru 1500
#multilink
#receive-all
ipcp-accept-local
ipcp-accept-remote
nopredictor1
noproxyarp
novj
novjccomp

ktune
mp
mppe-stateful


" > $uetc/ppp/provideruconf

#ln -s $uetc/ppp/provider /etc/ppp/peers/provideruconf
