#!/bin/bash
source /white-door/config/ddns-duckdns.txt

if [ "$enabled" = 1 ];
then
internetipv4=`curl ahmetozer.org/cdn-cgi/tracert -s | grep ip | cut -d'=' -f2`
/usr/bin/curl -k "$url$internetipv4"  &> /dev/null
fi