#!/bin/sh

# Create new resolv file
rm -rf /etc/resolv.conf

echo "nameserver 2606:4700:4700::1111
nameserver 2001:470:20::2
#nameserver 2001:4860:4860::8888
#nameserver 2606:4700:4700::1001
#nameserver 2001:4860:4860::8844
nameserver 1.1.1.1
#nameserver 74.82.42.42
#nameserver 8.8.8.8
#nameserver 1.0.0.1
nameserver 8.8.4.4" > /etc/resolv.conf

# Tunnel Broker Permissions
touch /white-door/config/tunnel-broker.txt
chmod 755 /white-door/config/tunnel-broker.txt

#Crontab
mkdir -p /var/spool/cron/crontabs


###
# Delete File
###
/white-door/sh/secondrun
mv /white-door/sh/secondrun /white-door/sh/startup