#!/bin/bash
urouter_dir="/urouter"
source $urouter_dir/urouter.uconf

echo "Son yapılan kontrol = $( date "+%d %B %A %Y Saat %H:%M:%S |%d-%m-%Y|")" >> $urouter_dir/logs/pppoe-disconnected.txt


ip route add default via dev $cableinterfaceuconf > /dev/null

source $ulang
echo $NTU3MzV | $uconfspeak

killall clatd -9
killall tayga -9
ip link delete clat

