#!/bin/sh
#Samba password
echo -e "toor\ntoor" | smbpasswd -a root

#Disable logging
mv /etc/init.d/S01logging /white-door/sh/old/etc/init.d/
#echo -e "#!/bin/sh\nexit 1" > /etc/init.d/S01logging

#Disable Radvd
mv /etc/init.d/S50radvd /white-door/sh/old/etc/init.d/

#Disable Stunnel
mv /etc/init.d/S50stunnel /white-door/sh/old/etc/init.d/

#Disable ptpd
mv /etc/init.d/S65ptpd /white-door/sh/old/etc/init.d/


# Create new resolv file
rm -rf /etc/resolv.conf

echo "nameserver 2606:4700:4700::1111
nameserver 2001:470:20::2
#nameserver 2001:4860:4860::8888
#nameserver 2606:4700:4700::1001
#nameserver 2001:4860:4860::8844

#nameserver 1.1.1.1
#nameserver 74.82.42.42
nameserver 8.8.8.8
#nameserver 1.0.0.1
nameserver 8.8.4.4" > /etc/resolv.conf

# Tunnel Broker Permissions
chmod 755 /white-door/config/tunnel-broker.txt

#NGINX SSL
echo -e "\n\n\n\n\n\n\n\n" | openssl req -newkey rsa:2048 -nodes -keyout /etc/nginx/domain.key -x509 -days 36500 -out /etc/nginx/domain.crt

openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048 -dsaparam

#Crontab
mkdir -p /var/spool/cron/crontabs

#Nginx passwduser
echo -n 'btn:' >> /etc/nginx/.htpasswd
echo -e "toor" | openssl passwd -apr1 -stdin >> /etc/nginx/.htpasswd

###
# Delete File
###
/white-door/sh/secondrun.sh
mv /white-door/sh/secondrun /white-door/sh/startup