#!/bin/sh
#
# Start logging
#

SYSLOGD_ARGS=-n
KLOGD_ARGS=-n
[ -r /etc/default/logging ] && . /etc/default/logging

start() {
	printf " \e[95m
#############################################
#                                           #
#        \e[107m \e[30mWhite Door Router Project \e[49m \e[95m       #
#                                           #
#                   \e[96mhttps://ahmetozer.org\e[95m   #
#############################################
\e[39m"

	printf "Starting : "
	start-stop-daemon -b -S -q -m -p /var/run/starter.pid --exec /white-door/sh/startup
	echo "OK"
}

stop() {
	printf "Stopping : "
	start-stop-daemon -K -q -p /var/run/starter.pid
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
